fixed overlapping buttons issue #335
razeware/emitron-Android pull request #337
Opened 2021-08-31 15:11 UTC by doraba

Fixed overlapping buttons in :
- fragment_login.xml 
- fragment_filter.xml
![fixed335issue](https://user-images.githubusercontent.com/36210089/131527937-70607bef-c453-4887-8c30-7cf1774db890.jpg)

2021-09-03 19:52 UTC, sammyd commented
Thanks for this! @rachitmishra please could you review this?

2021-09-04 11:36 UTC, rachitmishra commented on .idea/deploymentTargetDropDown.xml
> +<?xml version="1.0" encoding="UTF-8"?>
fix: seems like an unrelated file change. kindly remove this one.

2021-09-04 11:37 UTC, rachitmishra commented on .idea/misc.xml
> +  <component name="DesignSurface">
fix: these seem to unrelated changes as per the scope of the PR. kindly remove them

2021-09-04 11:38 UTC, rachitmishra requested changes

2021-09-04 11:38 UTC, rachitmishra commented on build.gradle
> +      'crashlytics'                 : '2.5.2',
fix: unrelated change as per scope of PR. Kindly revert this one.

2021-09-04 11:38 UTC, rachitmishra commented on model/build.gradle
> -    versionName "1.0"
fix: unrelated change as per scope of PR. Kindly revert this one.

2021-09-04 11:38 UTC, rachitmishra commented on inappreview/build.gradle
> -    versionName "1.0"
fix: unrelated change as per scope of PR. Kindly revert this one.

2021-09-04 11:38 UTC, rachitmishra commented on styles/build.gradle
> -    versionName "1.0"
fix: unrelated change as per scope of PR. Kindly revert this one.

2021-09-04 11:38 UTC, rachitmishra commented on styles/src/main/res/values/dimens.xml
> -  <dimen name="guideline_bottom_gesture">16dp</dimen>
curious? have we tested this on non-gesture devices, won't this break and add extra spacing in case of 3 button navigation?

2021-09-04 16:58 UTC, doraba commented on styles/src/main/res/values/dimens.xml
> -  <dimen name="guideline_bottom_gesture">16dp</dimen>
@rachitmishra Indeed, in cases without 3 button navigation, there was a little extra space left below. Thank you for all the useful feedback, I revisited the code according to your comments.

2022-07-30 01:15 UTC, closed without merging